Repository stackabletech/operator-rs, pull requests merged in 2021-06, with the labels that each got.

#131 Moved exists method from crd.rs to client.rs.
  src/client.rs
  src/crd.rs
  tests/test_crd.rs
Labels: priority/medium, type/enhancement

#139 Controller improvements
  src/role_utils.rs
Labels: priority/high, type/enhancement

#120 Update kube* from 0.52 to 0.56
  .github/workflows/rust.yml
  Cargo.toml
  src/client.rs
  src/command_controller.rs
  src/conditions.rs
  src/config_map.rs
  src/labels.rs
  src/metadata.rs
  src/pod_utils.rs
  src/reconcile.rs
  tests/test_crd.rs
Labels: priority/low, type/dependencies

#142 Work on TODOs
  src/pod_utils.rs
  src/reconcile.rs
  src/validation.rs
Labels: priority/low, type/enhancement

#145 Added Conditions to common status traits
  src/lib.rs
  src/status.rs
Labels: priority/high, type/enhancement

#148 Readd accidentally removed tests
  .github/workflows/rust.yml
Labels: priority/low, type/bug

#141 Common structs : convert role configuration to something better suited for the product configuration
  .gitignore
  src/krustlet.rs
  src/role_utils.rs
Labels: type/enhancement, type/question

#154 Added product config helper methods to transform role and group config…
  Cargo.toml
  src/client.rs
  src/crd.rs
  src/k8s_utils.rs
  src/lib.rs
  src/product_config_utils.rs
  src/role_utils.rs
  src/validation.rs
Labels: priority/high, type/enhancement

#146 Update kube-rs to 0.57 and k8s-openapi to 0.12
  Cargo.toml
  src/client.rs
  src/config_map.rs
  src/controller_ref.rs
  src/finalizer.rs
  src/krustlet.rs
  src/label_selector.rs
  src/metadata.rs
  src/pod_utils.rs
  src/reconcile.rs
  src/test.rs
Labels: priority/medium, type/enhancement
