Repository stackabletech/operator-rs, pull requests merged in 2021-09, with the labels that each got.

#203 Project update
  .github/pull_request_template.md
  .github/workflows/rust.yml
  CHANGELOG.md
  README.adoc
  deny.toml
Labels: type/enhancement, priority/low

#211 Extracted the versioning from the operators, added required traits for generic access
  CHANGELOG.md
  src/cli.rs
  src/lib.rs
  src/name_utils.rs
  src/status.rs
  src/versioning.rs
Labels: type/enhancement, priority/high

#210 Implement sticky scheduling
  CHANGELOG.md
  src/error.rs
  src/lib.rs
  src/name_utils.rs
  src/role_utils.rs
  src/scheduler.rs
Labels: type/enhancement

#215 Implement getter for PodIdentity fields.
  CHANGELOG.md
  Cargo.toml
  src/scheduler.rs
Labels: type/enhancement

#186 Update to kube-rs 0.59
  CHANGELOG.md
  Cargo.toml
  src/builder.rs
  src/client.rs
  src/command_controller.rs
  src/conditions.rs
  src/configmap.rs
  src/controller_ref.rs
  src/crd.rs
  src/finalizer.rs
  src/k8s_utils.rs
  src/krustlet.rs
  src/label_selector.rs
  src/pod_utils.rs
  src/reconcile.rs
  src/role_utils.rs
  src/scheduler.rs
  src/versioning.rs
  tests/test_crd.rs
Labels: type/enhancement, priority/high

#217 Bumped kube-rs to 0.60
  CHANGELOG.md
  Cargo.toml
  src/builder.rs
Labels: priority/medium, type/dependencies
