Repository stackabletech/operator-rs, pull requests merged in 2021-08, with the labels that each got.

#188 create_command_controller returns Result
  src/command_controller.rs
Labels: type/enhancement, priority/low

#190 Fix command controller
  src/command_controller.rs
Labels: type/bug, priority/critical

#191 Set log level to info by default/issue189
  src/logging.rs
Labels: type/enhancement

#192 Adds a simple method to print startup diagnostic information
  src/lib.rs
  src/utils.rs
Labels: type/enhancement, priority/low

#187 Adding methods to deal with CRDs in CLI interfaces
  src/cli.rs
Labels: type/enhancement, priority/medium

#199 Added PodSecurityContextBuilder
  src/builder.rs
Labels: type/enhancement

#198 Resource name generation
  Cargo.toml
  src/error.rs
  src/lib.rs
  src/name_utils.rs
  src/pod_utils.rs
Labels: type/enhancement, priority/medium

#200 Added windows security context properties.
  src/builder.rs
Labels: type/enhancement
