Repository stackabletech/operator-rs, pull requests merged in 2021-04, with the labels that each got.

#90 Adds a Schema for LabelSelector
  src/conditions.rs
  src/label_selector.rs
Labels: type: enhancement

#78 Many new methods to deal with common Operator operations
  Cargo.toml
  src/client.rs
  src/controller.rs
  src/k8s_utils.rs
  src/krustlet.rs
  src/labels.rs
  src/lib.rs
  src/podutils.rs
  src/reconcile.rs
  src/role_utils.rs
  src/test.rs
Labels: type: enhancement

#92 Rename podutils to pod_utils
  Cargo.toml
  src/client.rs
  src/k8s_utils.rs
  src/lib.rs
  src/pod_utils.rs
  src/reconcile.rs
Labels: type: enhancement

#87 Generic command controller for custom resource command objects; kube version bump to 0.51
  Cargo.toml
  src/command_controller.rs
  src/error.rs
  src/lib.rs
Labels: dependencies, type: enhancement

#95 Added automatic support for app.kubernetes.io/instance label in build_metadata
  src/labels.rs
  src/metadata.rs
Labels: type: enhancement

#93 feature: Namespace support
  src/error.rs
  src/lib.rs
  src/namespace.rs
  src/validation.rs
Labels: priority/medium, type/enhancement

#97 Code optimisation
  src/command_controller.rs
  src/config_map.rs
  src/crd.rs
  src/finalizer.rs
  src/history.rs
  src/metadata.rs
  src/role_utils.rs
  tests/test_crd.rs
Labels: priority/low

#98 Adapted to meta changes in kube rs 0.52
  Cargo.toml
  src/client.rs
  src/command_controller.rs
  src/conditions.rs
  src/config_map.rs
  src/controller.rs
  src/controller_ref.rs
  src/finalizer.rs
  src/history.rs
  src/labels.rs
  src/metadata.rs
  src/namespace.rs
  src/pod_utils.rs
  src/reconcile.rs
  tests/test_crd.rs
Labels: priority/high, type/enhancement
