Repository stackabletech/operator-rs, pull requests merged in 2021-02, with the labels that each got.

#52 Update kube & kube-runtime to 0.49
  Cargo.toml
Labels: enhancement

#56 This filters pods by owner reference of the current object.
  src/reconcile.rs
Labels: bug

#54 Improve logging
  Cargo.toml
  src/controller.rs
Labels: enhancement

#59 feature: Adds a is_pod_assigned_to_node function
  src/podutils.rs
Labels: enhancement

#61 fix: object_to_owner_reference now sets the controller flag.
  src/lib.rs
  src/metadata.rs
Labels: bug

#60 feature: ControllerStrategy::init_reconcile_state is now async and returns Result
  Cargo.toml
  src/controller.rs
Labels: type: enhancement

#63 Better error handling in Controller
  src/controller.rs
Labels: type: enhancement

#66 Update documentation
  src/client.rs
Labels: type: documentation

#64 added apply_patch_status method using Merge strategy
  src/client.rs
Labels: priority: high, type: enhancement

#62 Optionally set the block_owner_deletion flag in OwnerReferences for automatic cleanup
  src/history.rs
  src/lib.rs
  src/metadata.rs
Labels: type: enhancement

#68 Removes the `derive` feature from kube
  Cargo.toml
Labels: type: bug

#69 Adds a compute_hash method
  src/controller_utils.rs
  src/lib.rs
Labels: type: enhancement

#70 Adds validation methods for well-formed names
  Cargo.toml
  src/lib.rs
  src/validation.rs
Labels: type: enhancement

#71 Adds helper methods to deal with Condition in Status
  Cargo.toml
  src/client.rs
  src/conditions.rs
  src/lib.rs
  src/reconcile.rs
Labels: type: enhancement
