Repository stackabletech/operator-rs, pull requests merged in 2021-07, with the labels that each got.

#156 Add Builder types for various Kubernetes objects
  src/builder.rs
  src/command_controller.rs
  src/config_map.rs
  src/k8s_utils.rs
  src/krustlet.rs
  src/labels.rs
  src/lib.rs
  src/metadata.rs
  src/pod_utils.rs
  src/product_config_utils.rs
  src/reconcile.rs
  src/role_utils.rs
  src/test.rs
Labels: priority/high, type/enhancement

#161 Adapt to product config interface
  src/error.rs
  src/labels.rs
  src/product_config_utils.rs
  src/reconcile.rs
  src/role_utils.rs
Labels: priority/high, type/enhancement

#96 Adapt Crd to latest kube-rs changes which automatically generates a schema
  src/command_controller.rs
  src/crd.rs
  src/error.rs
  src/lib.rs
  tests/test_crd.rs
Labels: priority/low, type/enhancement

#168 Add method to create a unified pod-name
  src/pod_utils.rs
Labels: type/bug

#169 Add container ports to builder
  src/builder.rs
Labels: type/enhancement

#167 Add cargo deny to CI
  .github/workflows/rust.yml
  deny.toml
Labels: priority/high, type/enhancement

#171 Added annotation support to ObjectMetaBuilder
  src/builder.rs
Labels: type/enhancement

#166 Use replicas field when scheduling pods
  Cargo.toml
  src/k8s_utils.rs
  src/reconcile.rs
  src/role_utils.rs
Labels: priority/critical, type/enhancement

#172 Added product_config_path to retrieve location of product-config prop…
  Cargo.toml
  src/cli.rs
  src/lib.rs
Labels: priority/medium, type/enhancement

#174 Lookup product config file. Fixes #173.
  Cargo.toml
  src/cli.rs
  src/error.rs
Labels: priority/high, type/enhancement

#175 container_port_name now always lowercase.
  src/builder.rs
Labels: priority/medium, type/enhancement

#177 RoleGroup replicas now are Option<u16>
  src/k8s_utils.rs
  src/product_config_utils.rs
  src/reconcile.rs
  src/role_utils.rs
Labels: priority/high, type/enhancement
