Repository stackabletech/operator-rs, pull requests merged in 2024-09, with the labels that each got.

#844 feat(stackable-versioned): Add support for type changes of fields
  crates/stackable-versioned-macros/src/attrs/common/item.rs
  crates/stackable-versioned-macros/src/attrs/field.rs
  crates/stackable-versioned-macros/src/attrs/variant.rs
  crates/stackable-versioned-macros/src/codegen/chain.rs
  crates/stackable-versioned-macros/src/codegen/common/item.rs
  crates/stackable-versioned-macros/src/codegen/venum/variant.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/field.rs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned-macros/tests/good/attributes_enum.rs
  crates/stackable-versioned-macros/tests/good/attributes_struct.rs
  crates/stackable-versioned-macros/tests/good/basic.rs
  crates/stackable-versioned-macros/tests/good/rename.rs
  crates/stackable-versioned/CHANGELOG.md
  crates/stackable-versioned/src/lib.rs
Labels: type/feature-new

#855 Unrequire affinity types
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/commons/affinity.rs
Labels: type/bug

#854 ci: Replace reviewdog with pre-commit
  .github/workflows/pr_pre-commit.yaml
  .github/workflows/reviewdog.yaml
  .pre-commit-config.yaml
Labels: type/internal-improvement

#859 feat(stackable-versioned): Add 'use super::*' to generated version module
  crates/stackable-versioned-macros/src/codegen/venum/mod.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs
  crates/stackable-versioned/CHANGELOG.md
Labels: type/feature-new

#857 feat(stackable-versioned): Add K8s specific features
  Cargo.lock
  Cargo.toml
  crates/stackable-versioned-macros/Cargo.toml
  crates/stackable-versioned-macros/src/attrs/common/container.rs
  crates/stackable-versioned-macros/src/codegen/common/container.rs
  crates/stackable-versioned-macros/src/codegen/common/item.rs
  crates/stackable-versioned-macros/src/codegen/common/mod.rs
  crates/stackable-versioned-macros/src/codegen/venum/mod.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs
  crates/stackable-versioned-macros/tests/default/fail/README.md
  crates/stackable-versioned-macros/tests/default/fail/deprecate.rs
  crates/stackable-versioned-macros/tests/default/fail/deprecate.stderr
  crates/stackable-versioned-macros/tests/default/fail/skip_from_all.rs
  crates/stackable-versioned-macros/tests/default/fail/skip_from_all.stderr
  crates/stackable-versioned-macros/tests/default/fail/skip_from_version.rs
  crates/stackable-versioned-macros/tests/default/fail/skip_from_version.stderr
  crates/stackable-versioned-macros/tests/default/pass/README.md
  crates/stackable-versioned-macros/tests/default/pass/attributes_enum.rs
  crates/stackable-versioned-macros/tests/default/pass/attributes_struct.rs
  crates/stackable-versioned-macros/tests/default/pass/basic.rs
  crates/stackable-versioned-macros/tests/default/pass/deprecate.rs
  crates/stackable-versioned-macros/tests/default/pass/rename.rs
  crates/stackable-versioned-macros/tests/default/pass/skip_from_version.rs
  crates/stackable-versioned-macros/tests/k8s/fail/crd.rs
  crates/stackable-versioned-macros/tests/k8s/fail/crd.stderr
  crates/stackable-versioned-macros/tests/k8s/pass/crd.rs
  crates/stackable-versioned-macros/tests/trybuild.rs
  crates/stackable-versioned/CHANGELOG.md
Labels: type/feature-new

#865 feat(stackable-versioned): Add from_name parameter validation
  crates/stackable-versioned-macros/src/attrs/common/item.rs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned-macros/tests/default/fail/changed.rs
  crates/stackable-versioned-macros/tests/default/fail/changed.stderr
  crates/stackable-versioned/CHANGELOG.md
Labels: type/feature-new

#873 feat(stackable-versioned): Forward selected kube args
  crates/stackable-versioned-macros/src/attrs/common/container.rs
  crates/stackable-versioned-macros/src/codegen/common/container.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned-macros/tests/k8s/pass/crd.rs
  crates/stackable-versioned/CHANGELOG.md
Labels: type/feature-new

#876 feat(stackable-versioned): Add conditional allow attr generation
  crates/stackable-versioned-macros/src/codegen/chain.rs
  crates/stackable-versioned-macros/src/codegen/common/item.rs
  crates/stackable-versioned-macros/src/codegen/venum/mod.rs
  crates/stackable-versioned-macros/src/codegen/venum/variant.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/field.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned-macros/tests/default/pass/deprecate_enum.rs
  crates/stackable-versioned-macros/tests/default/pass/deprecate_struct.rs
  crates/stackable-versioned-macros/tests/trybuild.rs
Labels: type/feature-new

#871 fix!: Avoid clashing volumes and mounts
  Cargo.lock
  Cargo.toml
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/Cargo.toml
  crates/stackable-operator/src/builder/pod/container.rs
  crates/stackable-operator/src/builder/pod/mod.rs
  crates/stackable-operator/src/commons/authentication/ldap.rs
  crates/stackable-operator/src/commons/s3/helpers.rs
  crates/stackable-operator/src/commons/s3/mod.rs
  crates/stackable-operator/src/commons/tls_verification.rs
  crates/stackable-operator/src/product_logging/framework.rs
Labels: type/bug
