Repository stackabletech/operator-rs, pull requests merged in 2024-05, with the labels that each got.

#764 feat: Add `stackable-versioned` and `k8s-version` crates for CRD versioning
  CHANGELOG.md
  Cargo.toml
  crates/k8s-version/CHANGELOG.md
  crates/k8s-version/Cargo.toml
  crates/k8s-version/README.md
  crates/k8s-version/src/api_version.rs
  crates/k8s-version/src/group.rs
  crates/k8s-version/src/level.rs
  crates/k8s-version/src/lib.rs
  crates/k8s-version/src/version.rs
  crates/stackable-versioned/CHANGELOG.md
  crates/stackable-versioned/Cargo.toml
  crates/stackable-versioned/src/attrs/container.rs
  crates/stackable-versioned/src/attrs/field.rs
  crates/stackable-versioned/src/attrs/mod.rs
  crates/stackable-versioned/src/consts.rs
  crates/stackable-versioned/src/gen/field.rs
  crates/stackable-versioned/src/gen/mod.rs
  crates/stackable-versioned/src/gen/venum.rs
  crates/stackable-versioned/src/gen/version.rs
  crates/stackable-versioned/src/gen/vstruct.rs
  crates/stackable-versioned/src/lib.rs
  crates/stackable-versioned/tests/basic.rs
Labels: demo-needed

#782 chore: Bump Rust dependencies and GitHub Actions
  .github/workflows/build.yml
  .github/workflows/reviewdog.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/k8s-version/CHANGELOG.md
  crates/stackable-certs/CHANGELOG.md
  crates/stackable-operator-derive/CHANGELOG.md
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/builder/event.rs
  crates/stackable-operator/src/builder/pod/mod.rs
  crates/stackable-operator/src/builder/pod/security.rs
  crates/stackable-operator/src/builder/pod/volume.rs
  crates/stackable-operator/src/config/merge.rs
  crates/stackable-operator/src/product_config_utils.rs
  crates/stackable-operator/src/product_logging/spec.rs
  crates/stackable-telemetry/CHANGELOG.md
  crates/stackable-versioned/CHANGELOG.md
  crates/stackable-webhook/CHANGELOG.md
  rust-toolchain.toml
Labels: dependencies

#773 Support specifying externalTrafficPolicy in Services created by listener-operator
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/cluster_resources.rs
  crates/stackable-operator/src/commons/listener.rs
Labels: changelog/crd-change, type/internal-debt

#784 feat(stackable-versioned): Improve action chain generation
  Cargo.lock
  crates/stackable-versioned/CHANGELOG.md
  crates/stackable-versioned/Cargo.toml
  crates/stackable-versioned/src/attrs/field.rs
  crates/stackable-versioned/src/gen/field.rs
  crates/stackable-versioned/src/gen/mod.rs
  crates/stackable-versioned/src/gen/neighbors.rs
  crates/stackable-versioned/src/gen/vstruct.rs
  crates/stackable-versioned/tests/basic.rs
Labels: type/feature-improvement
