Repository stackabletech/operator-rs, pull requests merged in 2024-11, with the labels that each got.

#910 fix!: Correctly construct OIDC endpoints
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/commons/authentication/oidc.rs
Labels: type/bug, scheduled-for/2024-11

#891 feat(stackable-versioned): Add support for modules
  .github/workflows/build.yml
  .github/workflows/pr_pre-commit.yaml
  Cargo.lock
  crates/stackable-versioned-macros/Cargo.toml
  crates/stackable-versioned-macros/fixtures/inputs/default/module.rs
  crates/stackable-versioned-macros/fixtures/inputs/default/module_preserve.rs
  crates/stackable-versioned-macros/fixtures/inputs/k8s/skip.rs
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@attribute_enum.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@attribute_struct.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@basic_struct.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@deprecate_enum.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@deprecate_struct.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@enum_data_simple.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@module.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@module_preserve.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@rename.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@skip_from_field.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@basic.rs.snap
  crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@skip.rs.snap
  crates/stackable-versioned-macros/src/attrs/common.rs
  crates/stackable-versioned-macros/src/attrs/common/container.rs
  crates/stackable-versioned-macros/src/attrs/common/item.rs
  crates/stackable-versioned-macros/src/attrs/common/mod.rs
  crates/stackable-versioned-macros/src/attrs/container.rs
  crates/stackable-versioned-macros/src/attrs/item/field.rs
  crates/stackable-versioned-macros/src/attrs/item/mod.rs
  crates/stackable-versioned-macros/src/attrs/item/variant.rs
  crates/stackable-versioned-macros/src/attrs/k8s.rs
  crates/stackable-versioned-macros/src/attrs/mod.rs
  crates/stackable-versioned-macros/src/attrs/module.rs
  crates/stackable-versioned-macros/src/codegen/chain.rs
  crates/stackable-versioned-macros/src/codegen/changes.rs
  crates/stackable-versioned-macros/src/codegen/common/container.rs
  crates/stackable-versioned-macros/src/codegen/common/item.rs
  crates/stackable-versioned-macros/src/codegen/common/mod.rs
  crates/stackable-versioned-macros/src/codegen/container/enum.rs
  crates/stackable-versioned-macros/src/codegen/container/mod.rs
  crates/stackable-versioned-macros/src/codegen/container/struct.rs
  crates/stackable-versioned-macros/src/codegen/item/field.rs
  crates/stackable-versioned-macros/src/codegen/item/mod.rs
  crates/stackable-versioned-macros/src/codegen/item/variant.rs
  crates/stackable-versioned-macros/src/codegen/mod.rs
  crates/stackable-versioned-macros/src/codegen/module.rs
  crates/stackable-versioned-macros/src/codegen/venum/mod.rs
  crates/stackable-versioned-macros/src/codegen/venum/variant.rs
  crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs
  crates/stackable-versioned-macros/src/consts.rs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned-macros/src/test_utils.rs
  crates/stackable-versioned-macros/src/utils.rs
  crates/stackable-versioned-macros/tests/default/fail/changed.stderr
  crates/stackable-versioned-macros/tests/default/fail/deprecate.stderr
  crates/stackable-versioned/CHANGELOG.md
  rust-toolchain.toml
Labels: type/feature-new

#909 Fixes accidentally deleted serviceaccount and rolebinding objects
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/commons/rbac.rs
Labels: release-note, scheduled-for/2024-11
