Repository stackabletech/operator-rs, pull requests merged in 2025-02, with the labels that each got.

#959 feat(stackable-operator/s3connection): Add region field defaulting to us-east-1
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/src/commons/s3/crd.rs
  crates/stackable-operator/src/commons/s3/helpers.rs
Labels: release/25.3.0

#962 chore(stackable-operator): Release 0.86.1
  Cargo.lock
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/Cargo.toml
Labels: scheduled-for/25.3.0

#966 docs(stackable-versioned): Improve various sections of docs
  crates/stackable-versioned-macros/src/lib.rs
  crates/stackable-versioned/README.md
Labels: area/documentation

#973 chore: Bump Rust version and workflow actions
  .github/ISSUE_TEMPLATE/release-workspace-members.md
  .github/workflows/build.yml
  .github/workflows/daily_security.yml
  .github/workflows/pr_pre-commit.yaml
  .github/workflows/publish-docs.yml
  rust-toolchain.toml
Labels: release/25.3.0

#974 chore: Release stackable-operator-0.87.0 and stackable-versioned-0.6.0
  Cargo.lock
  crates/stackable-operator/CHANGELOG.md
  crates/stackable-operator/Cargo.toml
  crates/stackable-versioned-macros/Cargo.toml
  crates/stackable-versioned/CHANGELOG.md
  crates/stackable-versioned/Cargo.toml
Labels: release/25.3.0
